package br.senai.sp.jandira.lazyproducts.dao.repository

import androidx.compose.runtime.Composable
import br.senai.sp.jandira.lazyproducts.model.Product


class ProductRepository {

    //torna tudo que esteja dentro em estático, ou seja, é compartilhado com todos os objetos
    companion object{
        var teste: String = "teste"
@Composable
        fun getProductList(): List<Product>{
            return listOf<Product>(
                Product(id = 1, name = "Mouse"),
                Product(id = 2, name = "Teclado"),
                Product(id = 3, name = "Monitor", price = 890.99),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora"),
                Product(id = 4, name = "Impressora")
            )
//            return products
        }
    }
}